pub static RESPONSE_INVALID_REQUEST:u8 = 129;
pub static RESPONSE_DATA: u8 = 1;



pub static URL_NEXT_MONTHS_LOCATION_POLLS: &str = "0";
pub static URL_NEXT_WEEKS_LOCATION_POLLS: &str = "1";
pub static URL_TOMORROWS_LOCATION_POLLS: &str = "2";
pub static URL_DAY_AFTER_TOMORROWS_LOCATION_POLLS: &str = "3";


pub static URL_THIS_MONTHS_LOCATION_POLL_RANKINGS: &str = "4";
pub static URL_THIS_WEEKS_LOCATION_POLL_RANKINGS: &str = "5";
pub static URL_TODAYS_LOCATION_POLL_RANKINGS: &str = "6";


pub static URL_LAST_MONTHS_LOCATION_POLL_RANKINGS: &str = "7";
pub static URL_LAST_WEEKS__LOCATION_POLL_RANKINGS: &str = "8";
pub static URL_YESTERDAYS_LOCATION_POLL_RANKINGS: &str = "9";
pub static URL_DAY_BEFORE_YESTERDAY_LOCATION_POLL_RANKINGS: &str = "_";




pub static URL_NEXT_MONTHS_CATEGORY_POLLS: &str = "a";
pub static URL_NEXT_WEEKS_CATEGORY_POLLS: &str = "b";
pub static URL_TOMORROWS_CATEGORY_POLLS: &str = "c";
pub static URL_DAY_AFTER_TOMORROWS_CATEGORY_POLLS: &str = "d";


pub static URL_THIS_MONTHS_CATEGORY_POLL_RANKINGS: &str = "e";
pub static URL_THIS_WEEKS_CATEGORY_POLL_RANKINGS: &str = "f";
pub static URL_TODAYS_CATEGORY_POLL_RANKINGS: &str = "g";


pub static URL_LAST_MONTHS_CATEGORY_POLL_RANKINGS: &str = "h";
pub static URL_LAST_WEEKS_CATEGORY_POLL_RANKINGS: &str = "i";
pub static URL_YESTERDAYS_CATEGORY_POLL_RANKINGS: &str = "j";
pub static URL_DAY_BEFORE_YESTERDAY_CATEGORY_POLL_RANKINGS: &str = "k";




pub static URL_NEXT_MONTHS_LOCATION_CATEGORY_POLLS: &str = "A";
pub static URL_NEXT_WEEKS_LOCATION_CATEGORY_POLLS: &str = "B";
pub static URL_TOMORROWS_LOCATION_CATEGORY_POLLS: &str = "C";
pub static URL_DAY_AFTER_TOMORROWS_LOCATION_CATEGORY_POLLS: &str = "D";


pub static URL_THIS_MONTHS_LOCATION_CATEGORY_POLL_RANKINGS: &str = "E";
pub static URL_THIS_WEEKS_LOCATION_CATEGORY_POLL_RANKINGS: &str = "F";
pub static URL_TODAYS_LOCATION_CATEGORY_POLL_RANKINGS: &str = "G";


pub static URL_LAST_MONTHS_LOCATION_CATEGORY_POLL_RANKINGS: &str = "H";
pub static URL_LAST_WEEKS_LOCATION_CATEGORY_POLL_RANKINGS: &str = "I";
pub static URL_YESTERDAYS_LOCATION_CATEGORY_POLL_RANKINGS: &str = "J";
pub static URL_DAY_BEFORE_LOCATION_YESTERDAY_CATEGORY_POLL_RANKINGS: &str = "K";


